import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/footerCard/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Noman Developer",
  description: "Generated by create next app"
}

export default function RootLayout({ children }) {

  return (

    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700&display=swap" />
      </head>
      <body className={inter.className}>

        {children}
        <Footer />
      </body>
    </html>

  );
}
